---
title: "Emily Liu_A2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(leaflet)
library(ggplot2)
library(censusapi)
library(devtools)
#install_github('walkerke/tigris')
library(tigris)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

smc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  )

smc_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P001001"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P001001
  )
```

```{r}
dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )

dec_vars_2010 <-
  listCensusMetadata(
    name = "2010/dec/pl",
    type = "variables"
  )

dec_vars_2020 %>% 
  filter(grepl("P1",name)) %>% 
  select(name, label) %>% 
  arrange(name)

dec_vars_2010 %>% 
  filter(grepl("P1",name)) %>% 
  select(name, label) %>% 
  arrange(name)
```
Map of North Fair Oaks based on 2010 data
```{r}
library(devtools)
install_github('walkerke/tigris')
library(tigris)

blocks_2020 <- blocks("CA", "San Mateo", year = 2020, progress_bar = F)

nfo_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "North Fair Oaks")

# nfo_pop_2020 <- smc_pop_2020 %>% 
#   left_join(blocks_2020 %>% select(block = GEOID20)) %>% 
#   st_as_sf() %>%
#   st_centroid() %>% 
#   .[nfo_boundary, ] %>% 
#   st_set_geometry(NULL) %>% 
#   left_join(blocks_2020 %>% select(block = GEOID20)) %>% 
#   st_as_sf()

nfo_pop_2020 <- smc_pop_2020 %>% 
  left_join(blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()

blocks_2010 <- blocks("CA", "San Mateo", year = 2010, progress_bar = F)

nfo_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "North Fair Oaks")

nfo_pop_2010 <- smc_pop_2010 %>% 
  left_join(blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(smc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf()

mapview(nfo_boundary) + mapview(nfo_pop_2010, alpha.regions = 0, color = "red", lwd = 2)
```
```{r}
nfo_pop_2020 <- blocks_2020 %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(blocks_2020 %>% select(GEOID20)) %>% 
  st_as_sf()

nfo_2020_intersect <- nfo_pop_2020 %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.)) %>% 
  st_intersection(
    nfo_boundary %>%
      select(block = GEOID20) %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = as.numeric(leftover_area / original_area),
    #pop_2020 = pop * perc_area
  )

# nfo_2020_reshaped <- nfo_2020_intersect %>%
#   st_drop_geometry() %>% 
#   group_by(block) %>% 
#   summarize(
#     pop_2020 = sum(___, na.rm=T) %>% round()
#   )

# pop_2010_2020 <- smc_blocks_2010 %>%
#    st_intersection(
#      smc_blocks_2020 %>%
#    mutate(
#      absolute_pop = nfo_pop_2020 - nfo_pop_2010
#    )
#  )
```


```{r}
```